{
 "title": "TCP Servers",
 "description": "TCP Server\nDA TCP Server ",
 "tags": [
  "hyli",
  "node",
  "tcp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(consensus_current_slot,app)"
    }
   },
   {
    "name": "validator",
    "label": "Validator",
    "query": {
     "query": "label_values(netmessage_delay_milliseconds_bucket{app=\"$node\"},validator_pubkey)"
    }
   },
   {
    "name": "server",
    "label": "TCP Server",
    "query": {
     "query": "label_values(tcp_server_message_emitted_total{app=\"$node\"},server_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TCP SERVER (TcpApiServer)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TCPServer Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcp_server_peers{app=~\"$node\", server_name=~\"TcpApiServer\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TCPServer Closed sockets",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  max_over_time(tcp_server_message_closed_total{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__range]) - \n  min_over_time(tcp_server_message_closed_total{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__range])\n)",
     "legendFormat": "{{server_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "TCPServer Errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  max_over_time(tcp_server_message_error_total{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__range]) - \n  min_over_time(tcp_server_message_error_total{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCPServer Message Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(tcp_server_message_emitted_total{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__rate_interval])",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "TCPServer Message Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "increase(tcp_server_message_received_total{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__rate_interval])",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "TCPServer Message Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(tcp_server_message_emitted_bytes_total{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__rate_interval])",
     "legendFormat": "received {{server_name}} B/s"
    }
   ]
  },
  {
   "title": "TCPServer Message Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(tcp_server_message_received_bytes_total{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__rate_interval])",
     "legendFormat": "received {{server_name}} B/s"
    }
   ]
  },
  {
   "title": "DA TCPServer Average Sent Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  rate(tcp_server_message_send_time_seconds_sum{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__rate_interval]) / \n  rate(tcp_server_message_send_time_seconds_count{app=~\"$node\", server_name=~\"TcpApiServer\"}[$__rate_interval])\n) * 1000",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  { "title": "DA TCP SERVER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "DA TCPServer Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcp_server_peers{app=~\"$node\", server_name=~\"DAServer-.*\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "DA TCPServer Closed sockets",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  max_over_time(tcp_server_message_closed_total{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__range]) - \n  min_over_time(tcp_server_message_closed_total{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__range])\n)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "DA TCPServer Errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  max_over_time(tcp_server_message_error_total{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__range]) - \n  min_over_time(tcp_server_message_error_total{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__range])\n)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "DA TCPServer Message Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "increase(tcp_server_message_emitted_total{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__rate_interval])",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "DA TCPServer Message Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "increase(tcp_server_message_received_total{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__rate_interval])",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "DA TCPServer Message Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(tcp_server_message_emitted_bytes_total{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__rate_interval])",
     "legendFormat": "received {{server_name}} B/s"
    }
   ]
  },
  {
   "title": "DA TCPServer Message Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(tcp_server_message_received_bytes_total{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__rate_interval])",
     "legendFormat": "received {{server_name}} B/s"
    }
   ]
  },
  {
   "title": "DA TCPServer Average Sent Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  rate(tcp_server_message_send_time_seconds_sum{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__rate_interval]) / \n  rate(tcp_server_message_send_time_seconds_count{app=~\"$node\", server_name=~\"DAServer-.*\"}[$__rate_interval])\n) * 1000",
     "legendFormat": "{{server_name}}"
    }
   ]
  }
 ]
}