{
 "title": "P2P",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(consensus_current_slot,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "P2P Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_server_peers{app=~\"$node\"}",
     "legendFormat": "{{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "Poison",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_server_poison_total",
     "legendFormat": "{{otel_scope_name}}[{{canal}}] - {{action}}"
    }
   ]
  },
  { "title": "P2P's TCP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "P2P TCPServer Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcp_server_peers{app=~\"$node\", server_name=~\"P2P-.*\"}",
     "legendFormat": "{{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "P2P TCPServer Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(p2p_server_tcp_event_total{type=\"error\"}[$__rate_interval])",
     "legendFormat": "{{otel_scope_name}}[{{canal}}]"
    }
   ]
  },
  {
   "title": "P2P TCPServer Closed sockets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(p2p_server_tcp_event_total{type=\"closed\"}[$__rate_interval])",
     "legendFormat": "{{otel_scope_name}}[{{canal}}]"
    }
   ]
  },
  {
   "title": "P2P TCPServer Closed sockets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  max_over_time(tcp_server_message_closed_total{app=~\"$node\", server_name=~\"P2P-.*\"}[$__range]) - \n  min_over_time(tcp_server_message_closed_total{app=~\"$node\", server_name=~\"P2P-.*\"}[$__range])\n)",
     "legendFormat": "{{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "P2P TCPServer Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  max_over_time(tcp_server_message_error_total{app=~\"$node\", server_name=~\"P2P-.*\"}[$__range]) - \n  min_over_time(tcp_server_message_error_total{app=~\"$node\", server_name=~\"P2P-.*\"}[$__range])\n)",
     "legendFormat": "{{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "P2P TCPServer Message Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "increase(tcp_server_message_emitted_total{app=~\"$node\", server_name=~\"P2P-.*\"}[$__rate_interval])",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "P2P TCPServer Message Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "increase(tcp_server_message_received_total{app=~\"$node\", server_name=~\"P2P-.*\"}[$__rate_interval])",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "P2P TCPServer Message Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(tcp_server_message_emitted_bytes_total{app=~\"$node\", server_name=~\"P2P-.*\"}[$__rate_interval])",
     "legendFormat": "received {{server_name}} B/s"
    }
   ]
  },
  {
   "title": "P2P TCPServer Message Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(tcp_server_message_received_bytes_total{app=~\"$node\", server_name=~\"P2P-.*\"}[$__rate_interval])",
     "legendFormat": "received {{server_name}} B/s"
    }
   ]
  },
  {
   "title": "P2P TCPServer Average Sent Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  rate(tcp_server_message_send_time_seconds_sum{app=~\"$node\", server_name=~\"P2P-.*\"}[$__rate_interval]) / \n  rate(tcp_server_message_send_time_seconds_count{app=~\"$node\", server_name=~\"P2P-.*\"}[$__rate_interval])\n) * 1000",
     "legendFormat": "{{server_name}}"
    }
   ]
  }
 ]
}