{
 "title": "App overview",
 "tags": [
  "system",
  "k8s",
  "app"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "loki", "query": "loki" },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=~\"$cluster\", namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "k8s_node",
    "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{cluster=~\"$cluster\",namespace=~\"$namespace\",node=~\"$k8s_node\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App CPU (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (pod, container, app) (rate(container_cpu_usage_seconds_total{k8s_node=~\"$k8s_node\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__rate_interval]) * on (cluster, namespace, pod) group_left(app) (kube_pod_labels{cluster=~\"$cluster\", namespace=~\"$namespace\", app=~\"$app\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Memory (working set)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod, pod_uid, app) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"} * on (cluster, namespace, pod) group_left(app) (kube_pod_labels{cluster=~\"$cluster\", namespace=~\"$namespace\", app=~\"$app\"}))",
     "legendFormat": "{{app}} / {{pod}}"
    }
   ]
  },
  {
   "title": "App Network per pod (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod, app) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", interface!~\"lo\"}[$__rate_interval]) * on (cluster, namespace, pod) group_left(app) (kube_pod_labels{cluster=~\"$cluster\", namespace=~\"$namespace\", app=~\"$app\"}))",
     "legendFormat": "{{app}} / {{pod}} rx"
    },
    {
     "expr": "sum by (pod, app) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", interface!~\"lo\"}[$__rate_interval]) * on (cluster, namespace, pod) group_left(app) (kube_pod_labels{cluster=~\"$cluster\", namespace=~\"$namespace\", app=~\"$app\"}))",
     "legendFormat": "{{app}} / {{pod}} tx"
    }
   ]
  },
  {
   "title": "App Restarts (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (app) (rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) * on (cluster, namespace, pod) group_left(app) (kube_pod_labels{cluster=~\"$cluster\", namespace=~\"$namespace\", app=~\"$app\"}))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Bus / Net messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Bus receive / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(app, client_id, pod) (rate(bus_receive_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{client_id}} {{pod}} ({{app}})"
    }
   ]
  },
  {
   "title": "Bus buffering",
   "type": "timeseries",
   "description": "(should be mostly at 0)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (app, msg, pod) ((sum by(app, client_id, msg, pod) (rate(bus_send_total{pod=\"hyli-node-gauvain-0\"}[$__rate_interval]))))\n-\nmin by(app, msg, pod) (sum by(app, client_id, msg, pod) (rate(bus_receive_total{pod=\"hyli-node-gauvain-0\"}[$__rate_interval])))",
     "legendFormat": "{{client_id}} {{pod}} ({{app}})"
    }
   ]
  },
  {
   "title": "Net message latency distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(le) (rate(netmessage_delay_milliseconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th percentile event loop latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, client_id, pod, branch, app) (rate(event_loop_latency_bucket{branch!=\"core_loop\"}[$__rate_interval])))",
     "legendFormat": "{{app}} / {{client_id}} / {{branch}} ({{pod}})"
    }
   ]
  },
  { "title": "K8s Warning Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Image Pull Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (involvedObject_name) (count_over_time({container=\"kubernetes-event-exporter\", cluster=~\"$cluster\"} | json | involvedObject_namespace=~\"$namespace\" | involvedObject_name=~\"$pod\" | reason=\"ImagePullBackOff\" | __error__=\"\"[$__interval]))",
     "legendFormat": "{{involvedObject_name}}"
    }
   ]
  },
  {
   "title": "Container Crashed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (involvedObject_name) (count_over_time({container=\"kubernetes-event-exporter\", cluster=~\"$cluster\"} | json | involvedObject_namespace=~\"$namespace\" | involvedObject_name=~\"$pod\" | reason=\"BackOff\" | __error__=\"\"[$__interval]))",
     "legendFormat": "{{involvedObject_name}}"
    }
   ]
  },
  {
   "title": "Container OOM Killed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (involvedObject_name) (count_over_time({container=\"kubernetes-event-exporter\", cluster=~\"$cluster\"} | json | involvedObject_namespace=~\"$namespace\" | involvedObject_name=~\"$pod\" | reason=~\"OOMKilled|OOMKilling\" | __error__=\"\"[$__interval]))",
     "legendFormat": "{{involvedObject_name}}"
    }
   ]
  },
  {
   "title": "Killing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (involvedObject_name) (count_over_time({container=\"kubernetes-event-exporter\", cluster=~\"$cluster\"} | json | involvedObject_namespace=~\"$namespace\" | involvedObject_name=~\"$pod\" | reason=\"Killing\" | __error__=\"\"[$__interval]))",
     "legendFormat": "{{involvedObject_name}}"
    }
   ]
  },
  {
   "title": "Schedule Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (involvedObject_name) (count_over_time({container=\"kubernetes-event-exporter\", cluster=~\"$cluster\"} | json | involvedObject_namespace=~\"$namespace\" | involvedObject_name=~\"$pod\" | reason=\"FailedScheduling\" | __error__=\"\"[$__interval]))",
     "legendFormat": "{{involvedObject_name}}"
    }
   ]
  },
  {
   "title": "Pod Evicted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (involvedObject_name) (count_over_time({container=\"kubernetes-event-exporter\", cluster=~\"$cluster\"} | json | involvedObject_namespace=~\"$namespace\" | involvedObject_name=~\"$pod\" | reason=~\"TaintManagerEviction|Evicted\" | __error__=\"\"[$__interval]))",
     "legendFormat": "{{involvedObject_name}}"
    }
   ]
  },
  {
   "title": "Warning logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"kubernetes-event-exporter\"}\n| json\n| label_format level=\"{{ if or (eq .reason \\\"OOMKilling\\\") (eq .reason \\\"Killing\\\") (eq .reason \\\"Evicted\\\") (eq .reason \\\"Failed\\\")}}error{{ else if or (eq .reason \\\"BackOff\\\")  (eq .reason \\\"Unhealthy\\\")  (eq .reason \\\"VolumeFailedDelete\\\") (eq .reason \\\"FailedMount\\\")}}warn{{ else }}info{{ end }}\"\n| line_format \"{{ if eq .level \\\"error\\\" }}💥{{ else if eq .level \\\"warn\\\" }}⚠️{{ else }}ℹ️{{ end }} {{ .reason }} • {{ .involvedObject_namespace }}/{{ .involvedObject_name }} • x{{ .count }} — {{ .message }}\"\n"
    }
   ]
  }
 ]
}