{
 "title": "Mempool (wip)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Bytes per lane / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(lane) (rate(consensus_lane_bytes[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(node_name, message_type) (rate(tcp_server_message_emitted_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(node_name, pod_uid) (rate(mempool_api_tx_total[$__rate_interval]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Disseminated bytes / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(mempool_data_proposal_disseminated_bytes_total[$__rate_interval])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "DP / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(node_name, pod_uid) (rate(mempool_created_data_proposals_total[$__rate_interval]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Processed DP / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(node_name, pod_uid) (rate(mempool_processed_dp_total[$__rate_interval]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Api Tx / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(node_name, pod_uid) (rate(mempool_api_tx_total[$__rate_interval]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}