{
 "title": "Node consensus deep dive",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_name", "label": "Node name", "query": { "query": "label_values(node_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Current consensus slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "consensus_current_slot{node_name=~\"$node_name\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Commit / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(consensus_commit_total{node_name=~\"$node_name\"}[$__rate_interval])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Consensus role",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "consensus_state{node_name=~\"$node_name\"}",
     "legendFormat": "{{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "Timeouts / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(consensus_on_timeout_ok_total{node_name=~\"$node_name\"}[$__rate_interval])",
     "legendFormat": "{{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "Consensus logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"hyli-node\",node_name=~\"$node_name\"} | json | target =~ `hyli::consens.*` | line_format `{{.pod}} {{.target}} {{.fields_message}}`"
    }
   ]
  }
 ]
}