{
 "title": "4Pg  Simple Dashboard",
 "description": "My PostgreSQL simple dashboard",
 "tags": [ "MyPg" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "MyInstance", "query": "postgres" },
   {
    "name": "MyVar",
    "query": "select  inet_server_addr() || ':' || inet_server_addr()"
   },
   {
    "name": "MyVar2",
    "query": "select  substring(version() for  position(',' in version())-1)  from pg_database"
   }
  ]
 },
 "panels": [
  {
   "title": "Connection Info",
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">${MyInstance:text} -- <b>$MyVar</b></div>"
   }
  },
  {
   "title": "Read Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts as time,\n  (sum(heap_blks_read+heap_blks_hit+idx_blks_read+idx_blks_hit)-lag(sum(heap_blks_read+heap_blks_hit+idx_blks_read+idx_blks_hit)) over (order by ts))/600 as value\nFROM pgstatspack_snap s, pgstatspack_tables t\nWHERE ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n   AND s.snapid=t.snapid\nGROUP BY ts\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts as time,\n  sum(count_star) as value,\n  case when working then 'Active' else '<IDLE>' end as metric\nFROM pgstatspack_snap s, pgstatspack_activity_v a\nWHERE ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n   AND s.snapid=a.snapid\nGROUP BY working, ts\nORDER BY ts ASC, 2 desc"
    }
   ]
  },
  {
   "title": "Space usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select ts as time,\n       sum(sizek)*1024 as Size \n  from pgstatspack_space_usage\n WHERE ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by ts\n order by ts\n"
    }
   ]
  },
  {
   "title": "Heap Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as time,\n       sum(t.heap_blks_hit)/sum(t.heap_blks_hit+t.heap_blks_read)*100 as value \n  FROM pgstatspack_tables t, pgstatspack_snap s\n WHERE t.snapid=s.snapid\n   AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by s.ts\n order by ts"
    }
   ]
  },
  {
   "title": "IDX Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as time,\n       sum(t.idx_blks_hit)/sum(t.idx_blks_hit+t.idx_blks_read)*100 as value \n  FROM pgstatspack_tables t, pgstatspack_snap s\n WHERE t.snapid=s.snapid\n   AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by s.ts\n order by s.ts\n"
    }
   ]
  },
  {
   "title": "Tuples OUT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select $__timeEpoch(ts),\n       'Read' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.seq_tup_read) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n         GROUP BY s.ts) sum_read\n where ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\nUNION\nselect $__timeEpoch(ts),\n       'Fetch' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.idx_tup_fetch) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n         GROUP BY s.ts) sum_read\n where ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n order by 1 asc, 2 desc\n"
    }
   ]
  },
  {
   "title": "Transactions /sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select ts as time,\n       'Commit' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(d.xact_commit) as val\n          FROM pgstatspack_database d, pgstatspack_snap s\n         WHERE d.snapid=s.snapid\n         GROUP BY s.ts) sum_comm\n where ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\nUNION\nselect ts as time,\n       'Rollback' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(d.xact_rollback) as val\n          FROM pgstatspack_database d, pgstatspack_snap s\n         WHERE d.snapid=s.snapid\n         GROUP BY s.ts) sum_comm\n where ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n order by 1 asc, 2 desc"
    }
   ]
  },
  {
   "title": "Toast Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as time,\n       sum(t.toast_blks_hit)/sum(t.toast_blks_hit+t.toast_blks_read)*100 as value \n  FROM pgstatspack_tables t, pgstatspack_snap s\n WHERE t.snapid=s.snapid\n   AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by s.ts\n having sum(t.toast_blks_hit+t.toast_blks_read)>0\n order by s.ts"
    }
   ]
  },
  {
   "title": "Tuples IN",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select ts as time,\n       'Inserted' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.n_tup_ins) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n           and ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n         GROUP BY s.ts) sum_read\nUNION\nselect ts as time,\n       'Updated' as metric,\n       greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.n_tup_upd) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n           AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n         GROUP BY s.ts) sum_read\nUNION\nselect ts as time,\n       'Deleted' as metric,\n       -greatest(val-lag(val) over (order by ts), 0) as value\n  from (SELECT ts, sum(t.n_tup_del) as val\n          FROM pgstatspack_tables t, pgstatspack_snap s\n         WHERE t.snapid=s.snapid\n           AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n         GROUP BY s.ts) sum_read\n order by 1 asc, 2 desc"
    }
   ]
  },
  {
   "title": "Heatmap (#Active)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from timest)/86400)*86400 as \"time\",\n  max(to_char(timest,' HH24')) as metric,\n  sum(val) as value\nFROM (SELECT ts as timest, sum(case working when true then 1 else 0 end) as val\n          FROM pgstatspack_snap s, pgstatspack_activity_v a\n         WHERE ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n           AND s.snapid=a.snapid\n         GROUP BY ts ) q\nGROUP BY floor(extract(epoch from timest)/3600)*3600,floor(extract(epoch from timest)/86400)*86400\nORDER BY floor(extract(epoch from timest)/3600)*3600,floor(extract(epoch from timest)/86400)*86400;"
    }
   ]
  },
  {
   "title": "Toast IDX Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts as time,\n       sum(t.tidx_blks_hit)/sum(t.tidx_blks_hit+t.tidx_blks_read)*100 as value \n  FROM pgstatspack_tables t, pgstatspack_snap s\n WHERE t.snapid=s.snapid\n   AND ts between to_timestamp($__unixEpochFrom()) and to_timestamp($__unixEpochTo())\n group by s.ts\n having sum(t.tidx_blks_hit+t.tidx_blks_read)>0\n order by s.ts"
    }
   ]
  },
  {
   "title": "Master - Connected Slaves",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() as time,\n       count(*) as value \n  FROM pg_stat_replication s\n group by now()\n"
    }
   ]
  },
  { "title": "$MyVar2", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 0, "y": 20 } },
  {
   "title": "This dashboard uses pgstatspack (https://www.meo.bogliolo.name/pub/pgstatspack-2.3.4.zip)",
   "type": "text",
   "gridPos": { "h": 1, "w": 10, "x": 10, "y": 20 }
  },
  { "title": "by Meo", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 20, "y": 20 } }
 ]
}