{
 "title": "TcpClients",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(consensus_current_slot{app=\"$node\"},$node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Catchupper TcpClient", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message Emitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "tcp_client_message_emitted_total{otel_scope_name=\"catchupper\"}",
     "legendFormat": "{{pod}} - {{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "Message Emitted Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "tcp_client_message_emitted_bytes_total{otel_scope_name=\"catchupper\"}",
     "legendFormat": "{{pod}} - {{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "Message Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "tcp_client_message_received_total{otel_scope_name=\"catchupper\"}",
     "legendFormat": "{{pod}} - {{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "Message Received Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "tcp_client_message_emitted_bytes_total{otel_scope_name=\"catchupper\"}",
     "legendFormat": "{{pod}} - {{otel_scope_name}}"
    }
   ]
  }
 ]
}