{
 "title": "Traces - Consensus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId", "label": "Trace ID" },
   { "name": "minSlot", "label": "Slot start", "query": "0" },
   { "name": "maxSlot", "label": "Slot end" }
  ]
 },
 "panels": [
  { "title": "Rounds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rounds",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "e4879c25", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service" ]
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "1ms",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ name=~\"start_round|TimeoutTick\" && span.slot >= $minSlot && ($maxSlot < $minSlot || span.slot <= $maxSlot) } | select(span.view)\n",
     "tableType": "spans"
    }
   ]
  },
  { "title": "Timeouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "TimeoutQC",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "filters": [
      { "id": "e4879c25", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service" ]
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "1ms",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ name=\"TimeoutTick\" && span.slot >= $minSlot && ($maxSlot < $minSlot || span.slot <= $maxSlot) } | select(span.view)\n",
     "tableType": "spans"
    }
   ]
  },
  { "title": "Trace view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Traces panel",
   "type": "traces",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "filters": [
      { "id": "288c8c91", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "${traceId}",
     "scenarioId": "trace",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Spans",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "filters": [
      { "id": "19da16a1", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{trace:id=\"$traceId\"} | select(span:name)",
     "spss": 30,
     "tableType": "spans"
    }
   ]
  }
 ]
}